### PR TITLE
EntityTamableFox recode and a few changes

### PR DESCRIPTION
**Pull request by itsfolf**
So, I noticed that there was a lot of bloat code on EntityTamableFox and decided to clean it up, I did so by clearing the default pathfinder goals so there's no need to override all those methods to remove calls to initializePathFinderGoals.
I also updated some of the pathfinder field values that were outdated (possibly from 1.14?) to the actual ones, this should make fox behavior work as expected.
Last, I added a config option for the anvil GUI as to keep a more vanilla like feel to the plugin and also improved the logic around the interact event handling.

### CODE REVIEW

**Comment by itsfolf** [comment]
Oh, I also removed the sleeping and choosenName values from the data as these are already handled by default, and added a field on language.yml to customize the foxes default name.

**Comment by SeanOMik** [comment]
Awesome, I'll take a look at it but honestly probably won't make a release of it until a next MC version or a bug. I don't really want to flood the resource page for better coding, that doesn't really effect the user experience _that_  much.

 Also in your comments you have class names that seem like they would be the actual name of the classes. Did you just make those names up or find them somewhere?

**Comment by itsfolf** [comment]
@SeanOMik They are the actual class names, I took them from the server obfuscation mappings
Also, I think you should at least add the option for disabling the anvil GUI, it's kinda out of place imo

**Comment by SeanOMik** [comment]
Yeah I will add a way to disable the AnvilGUI. And where did you get the server obfuscation mappings? I've never heard of them.

**Comment by itsfolf** [comment]
@SeanOMilk you can find a url in the .minecraft/versions/version.json under "mappings" and "serverMappings"

**Pull request merged**
